# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Christy Presler
email: hello@christypresler.com
description: > # this means to ignore newlines until "baseurl:"
  Christy Presler is a Web Developer and Designer who is passionate about building intuitive user experiences that solve real problems for people.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: "@cnpresler"
github_username:  "cpresler"
linkedin_url: "https://www.linkedin.com/pub/christy-presler/86/148/575"
behance_username: "cnpresler"

# Build settings
markdown: kramdown
destination: _deploy
host: localhost

# Collections
collections:
- history
- resume_sections
- portfolio